resolver: lts-22.29

packages:
  - .

allow-newer: true

system-ghc: true

extra-deps:
  - git: https://github.com/eir-forsakring/structural-xml
    commit: f83c571f235c1ef3aee275078b004c36234eb2a7
  - git: https://github.com/eir-forsakring/hs-connection
    commit: cf3255a6f961ecfdb90579ff1cd39a42fe39d093

flags:
  cryptonite:
    use_target_attributes: false

ghc-options:
  "$locals": -fwrite-ide-info
    -hiedir=.hie
